# Generated by Django 5.0.7 on 2024-09-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('monitoring_id', models.AutoField(primary_key=True, serialize=False)),
                ('drainage_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
