# Generated by Django 4.2.16 on 2024-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageSystem',
            fields=[
                ('Drainage_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=100)),
                ('waterlevel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waterpressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
